/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kortforsyningen_proj_Proj */

#ifndef _Included_org_kortforsyningen_proj_Proj
#define _Included_org_kortforsyningen_proj_Proj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kortforsyningen_proj_Proj
 * Method:    createFromUserInput
 * Signature: (Ljava/lang/String;J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_kortforsyningen_proj_Proj_createFromUserInput
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
