/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osgeo_proj_CompoundCS */

#ifndef _Included_org_osgeo_proj_CompoundCS
#define _Included_org_osgeo_proj_CompoundCS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osgeo_proj_CompoundCS
 * Method:    getDimension
 * Signature: (Lorg/osgeo/proj/SharedPointer;)I
 */
JNIEXPORT jint JNICALL Java_org_osgeo_proj_CompoundCS_getDimension
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_osgeo_proj_CompoundCS
 * Method:    getAxis
 * Signature: (Lorg/osgeo/proj/SharedPointer;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_osgeo_proj_CompoundCS_getAxis
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
