/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osgeo_proj_Transform */

#ifndef _Included_org_osgeo_proj_Transform
#define _Included_org_osgeo_proj_Transform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osgeo_proj_Transform
 * Method:    assign
 * Signature: (Lorg/osgeo/proj/Context;)V
 */
JNIEXPORT void JNICALL Java_org_osgeo_proj_Transform_assign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_osgeo_proj_Transform
 * Method:    transform
 * Signature: (I[DII)V
 */
JNIEXPORT void JNICALL Java_org_osgeo_proj_Transform_transform
  (JNIEnv *, jobject, jint, jdoubleArray, jint, jint);

/*
 * Class:     org_osgeo_proj_Transform
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_osgeo_proj_Transform_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
