/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kortforsyningen_proj_Context */

#ifndef _Included_org_kortforsyningen_proj_Context
#define _Included_org_kortforsyningen_proj_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kortforsyningen_proj_Context
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_kortforsyningen_proj_Context_create
  (JNIEnv *, jclass);

/*
 * Class:     org_kortforsyningen_proj_Context
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_kortforsyningen_proj_Context_destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
