/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kortforsyningen_proj_SharedObject */

#ifndef _Included_org_kortforsyningen_proj_SharedObject
#define _Included_org_kortforsyningen_proj_SharedObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kortforsyningen_proj_SharedObject
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_kortforsyningen_proj_SharedObject_release
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
