/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osgeo_proj_ObjectFactory */

#ifndef _Included_org_osgeo_proj_ObjectFactory
#define _Included_org_osgeo_proj_ObjectFactory
#ifdef __cplusplus
extern "C" {
#endif
#undef org_osgeo_proj_ObjectFactory_NAME
#define org_osgeo_proj_ObjectFactory_NAME 0L
#undef org_osgeo_proj_ObjectFactory_IDENTIFIER
#define org_osgeo_proj_ObjectFactory_IDENTIFIER 1L
#undef org_osgeo_proj_ObjectFactory_CODESPACE
#define org_osgeo_proj_ObjectFactory_CODESPACE 2L
#undef org_osgeo_proj_ObjectFactory_ALIAS
#define org_osgeo_proj_ObjectFactory_ALIAS 3L
#undef org_osgeo_proj_ObjectFactory_REMARKS
#define org_osgeo_proj_ObjectFactory_REMARKS 4L
#undef org_osgeo_proj_ObjectFactory_DEPRECATED
#define org_osgeo_proj_ObjectFactory_DEPRECATED 5L
#undef org_osgeo_proj_ObjectFactory_ANCHOR_POINT
#define org_osgeo_proj_ObjectFactory_ANCHOR_POINT 6L
#undef org_osgeo_proj_ObjectFactory_SCOPE
#define org_osgeo_proj_ObjectFactory_SCOPE 7L
/*
 * Class:     org_osgeo_proj_ObjectFactory
 * Method:    create
 * Signature: ([Ljava/lang/String;[Lorg/osgeo/proj/SharedPointer;[Ljava/lang/String;[DIS)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_osgeo_proj_ObjectFactory_create
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jdoubleArray, jint, jshort);

#ifdef __cplusplus
}
#endif
#endif
