/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kortforsyningen_proj_Context */

#ifndef _Included_org_kortforsyningen_proj_Context
#define _Included_org_kortforsyningen_proj_Context
#ifdef __cplusplus
extern "C" {
#endif
#undef org_kortforsyningen_proj_Context_TIMEOUT
#define org_kortforsyningen_proj_Context_TIMEOUT 60000000000LL
/*
 * Class:     org_kortforsyningen_proj_Context
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_kortforsyningen_proj_Context_create
  (JNIEnv *, jclass);

/*
 * Class:     org_kortforsyningen_proj_Context
 * Method:    createFromUserInput
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_kortforsyningen_proj_Context_createFromUserInput
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kortforsyningen_proj_Context
 * Method:    createPJ
 * Signature: (Lorg/kortforsyningen/proj/Operation;)J
 */
JNIEXPORT jlong JNICALL Java_org_kortforsyningen_proj_Context_createPJ
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kortforsyningen_proj_Context
 * Method:    destroyPJ
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kortforsyningen_proj_Context_destroyPJ
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
