/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_osgeo_proj_ReferencingFormat */

#ifndef _Included_org_osgeo_proj_ReferencingFormat
#define _Included_org_osgeo_proj_ReferencingFormat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_osgeo_proj_ReferencingFormat
 * Method:    parse
 * Signature: (Ljava/lang/String;Lorg/osgeo/proj/Context;IZ)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_osgeo_proj_ReferencingFormat_parse
  (JNIEnv *, jobject, jstring, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
