/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kortforsyningen_proj_AuthorityFactory */

#ifndef _Included_org_kortforsyningen_proj_AuthorityFactory
#define _Included_org_kortforsyningen_proj_AuthorityFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kortforsyningen_proj_AuthorityFactory
 * Method:    newInstance
 * Signature: (Lorg/kortforsyningen/proj/Context;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_kortforsyningen_proj_AuthorityFactory_newInstance
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     org_kortforsyningen_proj_AuthorityFactory
 * Method:    getDescriptionText
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kortforsyningen_proj_AuthorityFactory_getDescriptionText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kortforsyningen_proj_AuthorityFactory
 * Method:    createGeodeticObject
 * Signature: (SLjava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_kortforsyningen_proj_AuthorityFactory_createGeodeticObject
  (JNIEnv *, jobject, jshort, jstring);

/*
 * Class:     org_kortforsyningen_proj_AuthorityFactory
 * Method:    createOperation
 * Signature: (Lorg/kortforsyningen/proj/NativeResource;Lorg/kortforsyningen/proj/NativeResource;DDDDDIIIIZ)Lorg/kortforsyningen/proj/Operation;
 */
JNIEXPORT jobject JNICALL Java_org_kortforsyningen_proj_AuthorityFactory_createOperation
  (JNIEnv *, jobject, jobject, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jint, jint, jint, jboolean);

/*
 * Class:     org_kortforsyningen_proj_AuthorityFactory
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kortforsyningen_proj_AuthorityFactory_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
