/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kortforsyningen_proj_NativeResource */

#ifndef _Included_org_kortforsyningen_proj_NativeResource
#define _Included_org_kortforsyningen_proj_NativeResource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kortforsyningen_proj_NativeResource
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kortforsyningen_proj_NativeResource_version
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
