/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kortforsyningen_proj_UnitOfMeasure */

#ifndef _Included_org_kortforsyningen_proj_UnitOfMeasure
#define _Included_org_kortforsyningen_proj_UnitOfMeasure
#ifdef __cplusplus
extern "C" {
#endif
#undef org_kortforsyningen_proj_UnitOfMeasure_SCALE_UNITY
#define org_kortforsyningen_proj_UnitOfMeasure_SCALE_UNITY 0L
#undef org_kortforsyningen_proj_UnitOfMeasure_PARTS_PER_MILLION
#define org_kortforsyningen_proj_UnitOfMeasure_PARTS_PER_MILLION 1L
#undef org_kortforsyningen_proj_UnitOfMeasure_METRE
#define org_kortforsyningen_proj_UnitOfMeasure_METRE 2L
#undef org_kortforsyningen_proj_UnitOfMeasure_RADIAN
#define org_kortforsyningen_proj_UnitOfMeasure_RADIAN 3L
#undef org_kortforsyningen_proj_UnitOfMeasure_MICRORADIAN
#define org_kortforsyningen_proj_UnitOfMeasure_MICRORADIAN 4L
#undef org_kortforsyningen_proj_UnitOfMeasure_DEGREE
#define org_kortforsyningen_proj_UnitOfMeasure_DEGREE 5L
#undef org_kortforsyningen_proj_UnitOfMeasure_ARC_SECOND
#define org_kortforsyningen_proj_UnitOfMeasure_ARC_SECOND 6L
#undef org_kortforsyningen_proj_UnitOfMeasure_GRAD
#define org_kortforsyningen_proj_UnitOfMeasure_GRAD 7L
#undef org_kortforsyningen_proj_UnitOfMeasure_SECOND
#define org_kortforsyningen_proj_UnitOfMeasure_SECOND 8L
#undef org_kortforsyningen_proj_UnitOfMeasure_YEAR
#define org_kortforsyningen_proj_UnitOfMeasure_YEAR 9L
/*
 * Class:     org_kortforsyningen_proj_UnitOfMeasure
 * Method:    create
 * Signature: (S)Lorg/kortforsyningen/proj/UnitOfMeasure;
 */
JNIEXPORT jobject JNICALL Java_org_kortforsyningen_proj_UnitOfMeasure_create
  (JNIEnv *, jclass, jshort);

#ifdef __cplusplus
}
#endif
#endif
