/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kortforsyningen_proj_BaseObject */

#ifndef _Included_org_kortforsyningen_proj_BaseObject
#define _Included_org_kortforsyningen_proj_BaseObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kortforsyningen_proj_BaseObject
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_kortforsyningen_proj_BaseObject_destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
