name: PROJ-JNI build and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Install PROJ
      run: sudo apt-get install proj-bin libproj-dev
    - name: Show PROJ version
      run: proj
    - name: Build with Maven
      run: mvn --batch-mode package
    - name: List contents of directory
      run: ls -l --human-readable --dereference target/
    - name: Verify module identification
      run: jar --describe-module --file target/proj-*.jar --release 9
    - name: Run tests
      run: java --class-path target/proj-1.0-SNAPSHOT.jar example/TransformPoints.java
