name: PROJ-JNI build and tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install sqlite3 and build-essential
      run: sudo apt-get install sqlite3 build-essential
    - name: Download PROJ
      run: wget https://download.osgeo.org/proj/proj-6.2.1.tar.gz
    - name: Extract PROJ source
      run: tar xf proj-6.2.1.tar.gz
    - name: Build and install PROJ
      run: |
        ./configure
        make -j `nproc`
        sudo make install
      working-directory: ./proj-6.2.1
    - name: Build with Maven
      run: mvn package
    - name: List contents of directory
      run: ls
    - name: Run tests
      run: java --class-path target/proj-1.0-SNAPSHOT.jar example/TransformPoints.java
